// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MsgDefine.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EGameEventCode int32

const (
	EGameEventCode_Code_Not_Enough_Gold EGameEventCode = 0
)

var EGameEventCode_name = map[int32]string{
	0: "Code_Not_Enough_Gold",
}
var EGameEventCode_value = map[string]int32{
	"Code_Not_Enough_Gold": 0,
}

func (x EGameEventCode) Enum() *EGameEventCode {
	p := new(EGameEventCode)
	*p = x
	return p
}
func (x EGameEventCode) String() string {
	return proto.EnumName(EGameEventCode_name, int32(x))
}
func (x *EGameEventCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGameEventCode_value, data, "EGameEventCode")
	if err != nil {
		return err
	}
	*x = EGameEventCode(value)
	return nil
}
func (EGameEventCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{0}
}

type Vector2 struct {
	X                    *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{0}
}
func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (dst *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(dst, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vector2) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type ReqLogin struct {
	AccountId            *string  `protobuf:"bytes,1,req,name=accountId" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{1}
}
func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (dst *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(dst, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

type AckLogin struct {
	ErrorCode            *int32   `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	Uid                  *int32   `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckLogin) Reset()         { *m = AckLogin{} }
func (m *AckLogin) String() string { return proto.CompactTextString(m) }
func (*AckLogin) ProtoMessage()    {}
func (*AckLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{2}
}
func (m *AckLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckLogin.Unmarshal(m, b)
}
func (m *AckLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckLogin.Marshal(b, m, deterministic)
}
func (dst *AckLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckLogin.Merge(dst, src)
}
func (m *AckLogin) XXX_Size() int {
	return xxx_messageInfo_AckLogin.Size(m)
}
func (m *AckLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_AckLogin.DiscardUnknown(m)
}

var xxx_messageInfo_AckLogin proto.InternalMessageInfo

func (m *AckLogin) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *AckLogin) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type ReqAckEnterRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAckEnterRoom) Reset()         { *m = ReqAckEnterRoom{} }
func (m *ReqAckEnterRoom) String() string { return proto.CompactTextString(m) }
func (*ReqAckEnterRoom) ProtoMessage()    {}
func (*ReqAckEnterRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{3}
}
func (m *ReqAckEnterRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAckEnterRoom.Unmarshal(m, b)
}
func (m *ReqAckEnterRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAckEnterRoom.Marshal(b, m, deterministic)
}
func (dst *ReqAckEnterRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAckEnterRoom.Merge(dst, src)
}
func (m *ReqAckEnterRoom) XXX_Size() int {
	return xxx_messageInfo_ReqAckEnterRoom.Size(m)
}
func (m *ReqAckEnterRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAckEnterRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAckEnterRoom proto.InternalMessageInfo

type ReqAckLeaveRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAckLeaveRoom) Reset()         { *m = ReqAckLeaveRoom{} }
func (m *ReqAckLeaveRoom) String() string { return proto.CompactTextString(m) }
func (*ReqAckLeaveRoom) ProtoMessage()    {}
func (*ReqAckLeaveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{4}
}
func (m *ReqAckLeaveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAckLeaveRoom.Unmarshal(m, b)
}
func (m *ReqAckLeaveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAckLeaveRoom.Marshal(b, m, deterministic)
}
func (dst *ReqAckLeaveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAckLeaveRoom.Merge(dst, src)
}
func (m *ReqAckLeaveRoom) XXX_Size() int {
	return xxx_messageInfo_ReqAckLeaveRoom.Size(m)
}
func (m *ReqAckLeaveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAckLeaveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAckLeaveRoom proto.InternalMessageInfo

type PlayerInfo struct {
	Gold                 *int32   `protobuf:"varint,6,opt,name=gold" json:"gold,omitempty"`
	Name                 *string  `protobuf:"bytes,13,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{5}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(dst, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *PlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type PlayerEntryInfo struct {
	Uid                  *int32      `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	TableIndex           *int32      `protobuf:"varint,2,req,name=table_index" json:"table_index,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,6,req,name=player_info" json:"player_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerEntryInfo) Reset()         { *m = PlayerEntryInfo{} }
func (m *PlayerEntryInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerEntryInfo) ProtoMessage()    {}
func (*PlayerEntryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{6}
}
func (m *PlayerEntryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerEntryInfo.Unmarshal(m, b)
}
func (m *PlayerEntryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerEntryInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerEntryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerEntryInfo.Merge(dst, src)
}
func (m *PlayerEntryInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerEntryInfo.Size(m)
}
func (m *PlayerEntryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerEntryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerEntryInfo proto.InternalMessageInfo

func (m *PlayerEntryInfo) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *PlayerEntryInfo) GetTableIndex() int32 {
	if m != nil && m.TableIndex != nil {
		return *m.TableIndex
	}
	return 0
}

func (m *PlayerEntryInfo) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type AckPlayerEntryList struct {
	ObjectList           []*PlayerEntryInfo `protobuf:"bytes,1,rep,name=object_list" json:"object_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AckPlayerEntryList) Reset()         { *m = AckPlayerEntryList{} }
func (m *AckPlayerEntryList) String() string { return proto.CompactTextString(m) }
func (*AckPlayerEntryList) ProtoMessage()    {}
func (*AckPlayerEntryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{7}
}
func (m *AckPlayerEntryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckPlayerEntryList.Unmarshal(m, b)
}
func (m *AckPlayerEntryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckPlayerEntryList.Marshal(b, m, deterministic)
}
func (dst *AckPlayerEntryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckPlayerEntryList.Merge(dst, src)
}
func (m *AckPlayerEntryList) XXX_Size() int {
	return xxx_messageInfo_AckPlayerEntryList.Size(m)
}
func (m *AckPlayerEntryList) XXX_DiscardUnknown() {
	xxx_messageInfo_AckPlayerEntryList.DiscardUnknown(m)
}

var xxx_messageInfo_AckPlayerEntryList proto.InternalMessageInfo

func (m *AckPlayerEntryList) GetObjectList() []*PlayerEntryInfo {
	if m != nil {
		return m.ObjectList
	}
	return nil
}

type AckPlayerLeaveList struct {
	ObjectList           []int32  `protobuf:"varint,1,rep,name=object_list" json:"object_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckPlayerLeaveList) Reset()         { *m = AckPlayerLeaveList{} }
func (m *AckPlayerLeaveList) String() string { return proto.CompactTextString(m) }
func (*AckPlayerLeaveList) ProtoMessage()    {}
func (*AckPlayerLeaveList) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{8}
}
func (m *AckPlayerLeaveList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckPlayerLeaveList.Unmarshal(m, b)
}
func (m *AckPlayerLeaveList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckPlayerLeaveList.Marshal(b, m, deterministic)
}
func (dst *AckPlayerLeaveList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckPlayerLeaveList.Merge(dst, src)
}
func (m *AckPlayerLeaveList) XXX_Size() int {
	return xxx_messageInfo_AckPlayerLeaveList.Size(m)
}
func (m *AckPlayerLeaveList) XXX_DiscardUnknown() {
	xxx_messageInfo_AckPlayerLeaveList.DiscardUnknown(m)
}

var xxx_messageInfo_AckPlayerLeaveList proto.InternalMessageInfo

func (m *AckPlayerLeaveList) GetObjectList() []int32 {
	if m != nil {
		return m.ObjectList
	}
	return nil
}

// 属性同步
type AckPublicPropertyList struct {
	Uid                  *int32      `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,2,req,name=player_info" json:"player_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AckPublicPropertyList) Reset()         { *m = AckPublicPropertyList{} }
func (m *AckPublicPropertyList) String() string { return proto.CompactTextString(m) }
func (*AckPublicPropertyList) ProtoMessage()    {}
func (*AckPublicPropertyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{9}
}
func (m *AckPublicPropertyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckPublicPropertyList.Unmarshal(m, b)
}
func (m *AckPublicPropertyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckPublicPropertyList.Marshal(b, m, deterministic)
}
func (dst *AckPublicPropertyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckPublicPropertyList.Merge(dst, src)
}
func (m *AckPublicPropertyList) XXX_Size() int {
	return xxx_messageInfo_AckPublicPropertyList.Size(m)
}
func (m *AckPublicPropertyList) XXX_DiscardUnknown() {
	xxx_messageInfo_AckPublicPropertyList.DiscardUnknown(m)
}

var xxx_messageInfo_AckPublicPropertyList proto.InternalMessageInfo

func (m *AckPublicPropertyList) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *AckPublicPropertyList) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type ReqAckBullet struct {
	Uid                  *int32   `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	BulletType           *int32   `protobuf:"varint,2,req,name=bullet_type" json:"bullet_type,omitempty"`
	Tpos                 *Vector2 `protobuf:"bytes,3,req,name=tpos" json:"tpos,omitempty"`
	SPos                 *Vector2 `protobuf:"bytes,4,req,name=sPos" json:"sPos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAckBullet) Reset()         { *m = ReqAckBullet{} }
func (m *ReqAckBullet) String() string { return proto.CompactTextString(m) }
func (*ReqAckBullet) ProtoMessage()    {}
func (*ReqAckBullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{10}
}
func (m *ReqAckBullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAckBullet.Unmarshal(m, b)
}
func (m *ReqAckBullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAckBullet.Marshal(b, m, deterministic)
}
func (dst *ReqAckBullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAckBullet.Merge(dst, src)
}
func (m *ReqAckBullet) XXX_Size() int {
	return xxx_messageInfo_ReqAckBullet.Size(m)
}
func (m *ReqAckBullet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAckBullet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAckBullet proto.InternalMessageInfo

func (m *ReqAckBullet) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *ReqAckBullet) GetBulletType() int32 {
	if m != nil && m.BulletType != nil {
		return *m.BulletType
	}
	return 0
}

func (m *ReqAckBullet) GetTpos() *Vector2 {
	if m != nil {
		return m.Tpos
	}
	return nil
}

func (m *ReqAckBullet) GetSPos() *Vector2 {
	if m != nil {
		return m.SPos
	}
	return nil
}

type AckFishOpt struct {
	FishId               *int32   `protobuf:"varint,1,req,name=fish_id" json:"fish_id,omitempty"`
	OptType              *int32   `protobuf:"varint,2,req,name=opt_type" json:"opt_type,omitempty"`
	PathId               *int32   `protobuf:"varint,3,opt,name=path_id" json:"path_id,omitempty"`
	FishConfigId         *int32   `protobuf:"varint,4,opt,name=fishConfigId" json:"fishConfigId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckFishOpt) Reset()         { *m = AckFishOpt{} }
func (m *AckFishOpt) String() string { return proto.CompactTextString(m) }
func (*AckFishOpt) ProtoMessage()    {}
func (*AckFishOpt) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{11}
}
func (m *AckFishOpt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckFishOpt.Unmarshal(m, b)
}
func (m *AckFishOpt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckFishOpt.Marshal(b, m, deterministic)
}
func (dst *AckFishOpt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckFishOpt.Merge(dst, src)
}
func (m *AckFishOpt) XXX_Size() int {
	return xxx_messageInfo_AckFishOpt.Size(m)
}
func (m *AckFishOpt) XXX_DiscardUnknown() {
	xxx_messageInfo_AckFishOpt.DiscardUnknown(m)
}

var xxx_messageInfo_AckFishOpt proto.InternalMessageInfo

func (m *AckFishOpt) GetFishId() int32 {
	if m != nil && m.FishId != nil {
		return *m.FishId
	}
	return 0
}

func (m *AckFishOpt) GetOptType() int32 {
	if m != nil && m.OptType != nil {
		return *m.OptType
	}
	return 0
}

func (m *AckFishOpt) GetPathId() int32 {
	if m != nil && m.PathId != nil {
		return *m.PathId
	}
	return 0
}

func (m *AckFishOpt) GetFishConfigId() int32 {
	if m != nil && m.FishConfigId != nil {
		return *m.FishConfigId
	}
	return 0
}

// 各种失败
type AckError struct {
	ErrorCode            *int32   `protobuf:"varint,1,req,name=error_code" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckError) Reset()         { *m = AckError{} }
func (m *AckError) String() string { return proto.CompactTextString(m) }
func (*AckError) ProtoMessage()    {}
func (*AckError) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{12}
}
func (m *AckError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckError.Unmarshal(m, b)
}
func (m *AckError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckError.Marshal(b, m, deterministic)
}
func (dst *AckError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckError.Merge(dst, src)
}
func (m *AckError) XXX_Size() int {
	return xxx_messageInfo_AckError.Size(m)
}
func (m *AckError) XXX_DiscardUnknown() {
	xxx_messageInfo_AckError.DiscardUnknown(m)
}

var xxx_messageInfo_AckError proto.InternalMessageInfo

func (m *AckError) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

type AckHitFish struct {
	Uid                  *int32   `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	FishId               *int32   `protobuf:"varint,2,req,name=fish_id" json:"fish_id,omitempty"`
	RewardGold           *int32   `protobuf:"varint,3,req,name=reward_gold" json:"reward_gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckHitFish) Reset()         { *m = AckHitFish{} }
func (m *AckHitFish) String() string { return proto.CompactTextString(m) }
func (*AckHitFish) ProtoMessage()    {}
func (*AckHitFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_MsgDefine_a855f4bd4b3ddbdd, []int{13}
}
func (m *AckHitFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckHitFish.Unmarshal(m, b)
}
func (m *AckHitFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckHitFish.Marshal(b, m, deterministic)
}
func (dst *AckHitFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckHitFish.Merge(dst, src)
}
func (m *AckHitFish) XXX_Size() int {
	return xxx_messageInfo_AckHitFish.Size(m)
}
func (m *AckHitFish) XXX_DiscardUnknown() {
	xxx_messageInfo_AckHitFish.DiscardUnknown(m)
}

var xxx_messageInfo_AckHitFish proto.InternalMessageInfo

func (m *AckHitFish) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *AckHitFish) GetFishId() int32 {
	if m != nil && m.FishId != nil {
		return *m.FishId
	}
	return 0
}

func (m *AckHitFish) GetRewardGold() int32 {
	if m != nil && m.RewardGold != nil {
		return *m.RewardGold
	}
	return 0
}

func init() {
	proto.RegisterType((*Vector2)(nil), "msg.Vector2")
	proto.RegisterType((*ReqLogin)(nil), "msg.ReqLogin")
	proto.RegisterType((*AckLogin)(nil), "msg.AckLogin")
	proto.RegisterType((*ReqAckEnterRoom)(nil), "msg.ReqAckEnterRoom")
	proto.RegisterType((*ReqAckLeaveRoom)(nil), "msg.ReqAckLeaveRoom")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*PlayerEntryInfo)(nil), "msg.PlayerEntryInfo")
	proto.RegisterType((*AckPlayerEntryList)(nil), "msg.AckPlayerEntryList")
	proto.RegisterType((*AckPlayerLeaveList)(nil), "msg.AckPlayerLeaveList")
	proto.RegisterType((*AckPublicPropertyList)(nil), "msg.AckPublicPropertyList")
	proto.RegisterType((*ReqAckBullet)(nil), "msg.ReqAckBullet")
	proto.RegisterType((*AckFishOpt)(nil), "msg.AckFishOpt")
	proto.RegisterType((*AckError)(nil), "msg.AckError")
	proto.RegisterType((*AckHitFish)(nil), "msg.AckHitFish")
	proto.RegisterEnum("msg.EGameEventCode", EGameEventCode_name, EGameEventCode_value)
}

func init() { proto.RegisterFile("MsgDefine.proto", fileDescriptor_MsgDefine_a855f4bd4b3ddbdd) }

var fileDescriptor_MsgDefine_a855f4bd4b3ddbdd = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x2d, 0x06, 0x12, 0x18, 0xd3, 0x3a, 0xd9, 0x50, 0x69, 0x15, 0xa9, 0x2d, 0xb2, 0x7a, 0x70,
	0x38, 0x70, 0xe0, 0x07, 0x22, 0x9a, 0xba, 0x29, 0x15, 0x6d, 0x11, 0x87, 0x48, 0x3d, 0x59, 0xc6,
	0x1e, 0xcc, 0x16, 0xb3, 0xe3, 0xac, 0xd7, 0x69, 0xf8, 0xfb, 0x6a, 0x97, 0x84, 0x40, 0xe9, 0x89,
	0x65, 0xe6, 0xcd, 0x7b, 0xf3, 0xc6, 0x0f, 0xbc, 0xef, 0x65, 0xf6, 0x19, 0x17, 0x42, 0xe2, 0xa0,
	0x50, 0xa4, 0x89, 0xd5, 0xd7, 0x65, 0xe6, 0x7f, 0x80, 0xd3, 0x3b, 0x4c, 0x34, 0xa9, 0x21, 0x6b,
	0x43, 0xed, 0x91, 0xd7, 0x7a, 0x4e, 0xe0, 0x98, 0xe7, 0x86, 0x3b, 0xe6, 0xe9, 0xbf, 0x83, 0xd6,
	0x0c, 0xef, 0x27, 0x94, 0x09, 0xc9, 0xce, 0xa1, 0x1d, 0x27, 0x09, 0x55, 0x52, 0x8f, 0x53, 0x8b,
	0x6c, 0xfb, 0x7d, 0x68, 0x8d, 0x92, 0xd5, 0xae, 0x8d, 0x4a, 0x91, 0xba, 0xa1, 0x14, 0x6d, 0xbb,
	0xc9, 0x5c, 0xa8, 0x57, 0x22, 0xe5, 0x4e, 0xaf, 0x16, 0x34, 0xfd, 0x73, 0xf0, 0x66, 0x78, 0x3f,
	0x4a, 0x56, 0xa1, 0xd4, 0xa8, 0x66, 0x44, 0xeb, 0x97, 0xd2, 0x04, 0xe3, 0x07, 0xb4, 0xa5, 0x00,
	0x60, 0x9a, 0xc7, 0x1b, 0x54, 0x63, 0xb9, 0x20, 0xd6, 0x81, 0x46, 0x46, 0x79, 0xca, 0x4f, 0x0c,
	0x83, 0xf9, 0x27, 0xe3, 0x35, 0xf2, 0xd7, 0xbd, 0x5a, 0xd0, 0xf6, 0x7f, 0x81, 0xb7, 0x45, 0x86,
	0x52, 0xab, 0x8d, 0x85, 0x3f, 0xe9, 0x6d, 0xc5, 0x2f, 0xc0, 0xd5, 0xf1, 0x3c, 0xc7, 0x48, 0xc8,
	0x14, 0x1f, 0xad, 0x9f, 0x26, 0xfb, 0x08, 0x6e, 0x61, 0x87, 0x22, 0x21, 0x17, 0xc4, 0x4f, 0x7a,
	0x4e, 0xe0, 0x0e, 0xbd, 0xc1, 0xba, 0xcc, 0x06, 0x2f, 0xb2, 0xfe, 0x35, 0xb0, 0x51, 0xb2, 0xda,
	0x63, 0x9f, 0x88, 0x52, 0xb3, 0x2b, 0x70, 0x69, 0xfe, 0x1b, 0x13, 0x1d, 0xe5, 0xa2, 0xd4, 0xbc,
	0xd6, 0xab, 0x07, 0xee, 0xb0, 0xbb, 0x37, 0xbb, 0x5b, 0xc4, 0xbf, 0xda, 0x23, 0xb0, 0xde, 0x2c,
	0xc1, 0xc5, 0x31, 0x41, 0xd3, 0xff, 0x06, 0x6f, 0x0d, 0xb4, 0x9a, 0xe7, 0x22, 0x99, 0x2a, 0x2a,
	0x50, 0xe9, 0xad, 0xdc, 0x81, 0x99, 0x7f, 0xf6, 0x76, 0xfe, 0xbf, 0xf7, 0x12, 0x3a, 0xdb, 0x7b,
	0x7e, 0xaa, 0xf2, 0x1c, 0xf5, 0xd1, 0x3d, 0xe6, 0xb6, 0x1c, 0xe9, 0x4d, 0x81, 0x4f, 0xf7, 0xb8,
	0x84, 0x86, 0x2e, 0xa8, 0xe4, 0x75, 0x4b, 0xd8, 0xb1, 0x84, 0xcf, 0x89, 0xb8, 0x84, 0x46, 0x39,
	0xa5, 0x92, 0x37, 0x8e, 0x7b, 0xfe, 0x1d, 0xc0, 0x28, 0x59, 0x7d, 0x11, 0xe5, 0xf2, 0x67, 0xa1,
	0x99, 0x07, 0xa7, 0x0b, 0x51, 0x2e, 0xa3, 0x9d, 0xd6, 0x19, 0xb4, 0xa8, 0x38, 0x10, 0xf2, 0xe0,
	0xb4, 0x88, 0xb5, 0x85, 0xd4, 0xed, 0xc7, 0xec, 0x42, 0xc7, 0xcc, 0xdc, 0x90, 0x5c, 0x88, 0x6c,
	0x9c, 0xf2, 0x86, 0x0d, 0xc9, 0x7b, 0x1b, 0xa8, 0xd0, 0xe4, 0x88, 0x31, 0x00, 0x1b, 0xa8, 0x28,
	0xd9, 0x25, 0xca, 0xbf, 0xb6, 0xba, 0x5f, 0x85, 0x36, 0xd2, 0x87, 0xfe, 0xf6, 0x96, 0x70, 0x9e,
	0x0d, 0x2b, 0xfc, 0x13, 0xab, 0x34, 0xb2, 0x19, 0x32, 0x16, 0x9b, 0xfd, 0x3e, 0xbc, 0x09, 0x6f,
	0xe3, 0x35, 0x86, 0x0f, 0x28, 0xb5, 0x89, 0x2a, 0xe3, 0xd0, 0x35, 0xbf, 0xd1, 0x0f, 0xd2, 0x51,
	0x28, 0xa9, 0xca, 0x96, 0xd1, 0x2d, 0xe5, 0xe9, 0xd9, 0xab, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0xa7, 0xf6, 0xb0, 0x34, 0x03, 0x00, 0x00,
}
